window.esdocSearchIndex = [
  [
    "./public/statefulpatterns.mjs~always",
    "variable/index.html#static-variable-ALWAYS",
    "<span>ALWAYS</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "variable"
  ],
  [
    "./public/csoundac.mjs~chord",
    "function/index.html#static-function-Chord",
    "<span>Chord</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "function"
  ],
  [
    "./public/csoundac.mjs~chordpatterns",
    "class/public/csoundac.mjs~ChordPatterns.html",
    "<span>ChordPatterns</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "class"
  ],
  [
    "./public/csoundac.mjs~clone",
    "function/index.html#static-function-Clone",
    "<span>Clone</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "function"
  ],
  [
    "./public/csoundaudionode.js~csoundaudionode",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html",
    "<span>CsoundAudioNode</span> <span class=\"search-result-import-path\">./public/CsoundAudioNode.js</span>",
    "class"
  ],
  [
    "./public/statefulpatterns.mjs~debug",
    "variable/index.html#static-variable-DEBUG",
    "<span>DEBUG</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "variable"
  ],
  [
    "./public/statefulpatterns.mjs~error",
    "variable/index.html#static-variable-ERROR",
    "<span>ERROR</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "variable"
  ],
  [
    "./public/statefulpatterns.mjs~information",
    "variable/index.html#static-variable-INFORMATION",
    "<span>INFORMATION</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "variable"
  ],
  [
    "./public/statefulpatterns.mjs~never",
    "variable/index.html#static-variable-NEVER",
    "<span>NEVER</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "variable"
  ],
  [
    "./public/csoundac.mjs~pitv",
    "function/index.html#static-function-Pitv",
    "<span>Pitv</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "function"
  ],
  [
    "./public/csoundac.mjs~pitvpatterns",
    "class/public/csoundac.mjs~PitvPatterns.html",
    "<span>PitvPatterns</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "class"
  ],
  [
    "./public/csoundac.mjs~scale",
    "function/index.html#static-function-Scale",
    "<span>Scale</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "function"
  ],
  [
    "./public/csoundac.mjs~scalepatterns",
    "class/public/csoundac.mjs~ScalePatterns.html",
    "<span>ScalePatterns</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "class"
  ],
  [
    "./public/statefulpatterns.mjs~statefulpatterns",
    "class/public/statefulpatterns.mjs~StatefulPatterns.html",
    "<span>StatefulPatterns</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "class"
  ],
  [
    "./public/statefulpatterns.mjs~warning",
    "variable/index.html#static-variable-WARNING",
    "<span>WARNING</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "variable"
  ],
  [
    "./public/csoundac.mjs~audiocontext",
    "variable/index.html#static-variable-audioContext",
    "<span>audioContext</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "variable"
  ],
  [
    "./public/statefulpatterns.mjs~audiocontext",
    "variable/index.html#static-variable-audioContext",
    "<span>audioContext</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "variable"
  ],
  [
    "./public/csoundac.mjs~chordn_counter",
    "variable/index.html#static-variable-chordn_counter",
    "<span>chordn_counter</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "variable"
  ],
  [
    "./public/csoundac.mjs~csound",
    "variable/index.html#static-variable-csound",
    "<span>csound</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "variable"
  ],
  [
    "./public/statefulpatterns.mjs~csound",
    "variable/index.html#static-variable-csound",
    "<span>csound</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "variable"
  ],
  [
    "./public/csoundac.mjs~csoundac",
    "variable/index.html#static-variable-csoundac",
    "<span>csoundac</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "variable"
  ],
  [
    "./public/statefulpatterns.mjs~csoundac",
    "variable/index.html#static-variable-csoundac",
    "<span>csoundac</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "variable"
  ],
  [
    "./public/csoundac.mjs~csoundn",
    "variable/index.html#static-variable-csoundn",
    "<span>csoundn</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "variable"
  ],
  [
    "./public/csoundac.mjs~csoundn_counter",
    "variable/index.html#static-variable-csoundn_counter",
    "<span>csoundn_counter</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "variable"
  ],
  [
    "./public/statefulpatterns.mjs~diagnostic",
    "function/index.html#static-function-diagnostic",
    "<span>diagnostic</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "function"
  ],
  [
    "./public/statefulpatterns.mjs~diagnostic_level",
    "function/index.html#static-function-diagnostic_level",
    "<span>diagnostic_level</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "function"
  ],
  [
    "./public/statefulpatterns.mjs~diagnostic_level_",
    "variable/index.html#static-variable-diagnostic_level_",
    "<span>diagnostic_level_</span> <span class=\"search-result-import-path\">./public/statefulpatterns.mjs</span>",
    "variable"
  ],
  [
    "./public/csoundac.mjs~frequencytomidiinteger",
    "function/index.html#static-function-frequencyToMidiInteger",
    "<span>frequencyToMidiInteger</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "function"
  ],
  [
    "./public/csoundac.mjs~frequencytomidireal",
    "function/index.html#static-function-frequencyToMidiReal",
    "<span>frequencyToMidiReal</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "function"
  ],
  [
    "./public/csoundac.mjs~getfrequency",
    "function/index.html#static-function-getFrequency",
    "<span>getFrequency</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "function"
  ],
  [
    "./public/csoundac.mjs~hsvtorgb",
    "function/index.html#static-function-hsvToRgb",
    "<span>hsvToRgb</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "function"
  ],
  [
    "./public/csoundac.mjs~instrument_count",
    "variable/index.html#static-variable-instrument_count",
    "<span>instrument_count</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "variable"
  ],
  [
    "./public/csoundac.mjs~print_counter",
    "function/index.html#static-function-print_counter",
    "<span>print_counter</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "function"
  ],
  [
    "./public/csoundac.mjs~setpitch",
    "function/index.html#static-function-setPitch",
    "<span>setPitch</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "function"
  ],
  [
    "./public/csoundac.mjs~set_instrument_count",
    "function/index.html#static-function-set_instrument_count",
    "<span>set_instrument_count</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "function"
  ],
  [
    "./public/csoundac.mjs~track",
    "function/index.html#static-function-track",
    "<span>track</span> <span class=\"search-result-import-path\">./public/csoundac.mjs</span>",
    "function"
  ],
  [
    "public/csoundaudionode.js",
    "file/public/CsoundAudioNode.js.html",
    "public/CsoundAudioNode.js",
    "file"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#cleanup",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-Cleanup",
    "public/CsoundAudioNode.js~CsoundAudioNode#Cleanup",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#cleanuppromise",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-CleanupPromise",
    "public/CsoundAudioNode.js~CsoundAudioNode#CleanupPromise",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#compilecsd",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-CompileCsd",
    "public/CsoundAudioNode.js~CsoundAudioNode#CompileCsd",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#compilecsdtext",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-CompileCsdText",
    "public/CsoundAudioNode.js~CsoundAudioNode#CompileCsdText",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#compilecsdtextpromise",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-CompileCsdTextPromise",
    "public/CsoundAudioNode.js~CsoundAudioNode#CompileCsdTextPromise",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#compileorc",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-CompileOrc",
    "public/CsoundAudioNode.js~CsoundAudioNode#CompileOrc",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#compileorcpromise",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-CompileOrcPromise",
    "public/CsoundAudioNode.js~CsoundAudioNode#CompileOrcPromise",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#destroy",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-Destroy",
    "public/CsoundAudioNode.js~CsoundAudioNode#Destroy",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#evalcode",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-EvalCode",
    "public/CsoundAudioNode.js~CsoundAudioNode#EvalCode",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#get0dbfs",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-Get0dBFS",
    "public/CsoundAudioNode.js~CsoundAudioNode#Get0dBFS",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getapiversion",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetAPIVersion",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetAPIVersion",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getcontrolchannel",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetControlChannel",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetControlChannel",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getcurrenttimesamples",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetCurrentTimeSamples",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetCurrentTimeSamples",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getenv",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetEnv",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetEnv",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getfiledata",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetFileData",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetFileData",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getfiledatapromise",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-GetFileDataPromise",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetFileDataPromise",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getgetcontrolchannelpromise",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-GetGetControlChannelPromise",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetGetControlChannelPromise",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getinputname",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetInputName",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetInputName",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getksmps",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetKsmps",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetKsmps",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getnchnls",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetNchnls",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetNchnls",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getnchnlsinput",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetNchnlsInput",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetNchnlsInput",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getoutputname",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetOutputName",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetOutputName",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getscoreoffsetseconds",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetScoreOffsetSeconds",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetScoreOffsetSeconds",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getscoretime",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetScoreTime",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetScoreTime",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getscoretimepromise",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-GetScoreTimePromise",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetScoreTimePromise",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getsr",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetSr",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetSr",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getstringchannel",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetStringChannel",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetStringChannel",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getversion",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-GetVersion",
    "public/CsoundAudioNode.js~CsoundAudioNode#GetVersion",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#inputmessage",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-InputMessage",
    "public/CsoundAudioNode.js~CsoundAudioNode#InputMessage",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#isplaying",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-IsPlaying",
    "public/CsoundAudioNode.js~CsoundAudioNode#IsPlaying",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#isplayingpromise",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-IsPlayingPromise",
    "public/CsoundAudioNode.js~CsoundAudioNode#IsPlayingPromise",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#isscorepending",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-IsScorePending",
    "public/CsoundAudioNode.js~CsoundAudioNode#IsScorePending",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#killinstance",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-KillInstance",
    "public/CsoundAudioNode.js~CsoundAudioNode#KillInstance",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#message",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-Message",
    "public/CsoundAudioNode.js~CsoundAudioNode#Message",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#perform",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-Perform",
    "public/CsoundAudioNode.js~CsoundAudioNode#Perform",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#performcsd",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-PerformCsd",
    "public/CsoundAudioNode.js~CsoundAudioNode#PerformCsd",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#performorc",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-PerformOrc",
    "public/CsoundAudioNode.js~CsoundAudioNode#PerformOrc",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#readscore",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-ReadScore",
    "public/CsoundAudioNode.js~CsoundAudioNode#ReadScore",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#readscorepromise",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-ReadScorePromise",
    "public/CsoundAudioNode.js~CsoundAudioNode#ReadScorePromise",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#reset",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-Reset",
    "public/CsoundAudioNode.js~CsoundAudioNode#Reset",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#resetpromise",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-ResetPromise",
    "public/CsoundAudioNode.js~CsoundAudioNode#ResetPromise",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#rewindscore",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-RewindScore",
    "public/CsoundAudioNode.js~CsoundAudioNode#RewindScore",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#setcontrolchannel",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-SetControlChannel",
    "public/CsoundAudioNode.js~CsoundAudioNode#SetControlChannel",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#setglobalenv",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-SetGlobalEnv",
    "public/CsoundAudioNode.js~CsoundAudioNode#SetGlobalEnv",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#setinput",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-SetInput",
    "public/CsoundAudioNode.js~CsoundAudioNode#SetInput",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#setmessagecallback",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-SetMessageCallback",
    "public/CsoundAudioNode.js~CsoundAudioNode#SetMessageCallback",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#setoption",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-SetOption",
    "public/CsoundAudioNode.js~CsoundAudioNode#SetOption",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#setoutput",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-SetOutput",
    "public/CsoundAudioNode.js~CsoundAudioNode#SetOutput",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#setscoreoffsetseconds",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-SetScoreOffsetSeconds",
    "public/CsoundAudioNode.js~CsoundAudioNode#SetScoreOffsetSeconds",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#setscorepending",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-SetScorePending",
    "public/CsoundAudioNode.js~CsoundAudioNode#SetScorePending",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#setstringchannel",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-SetStringChannel",
    "public/CsoundAudioNode.js~CsoundAudioNode#SetStringChannel",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#start",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-Start",
    "public/CsoundAudioNode.js~CsoundAudioNode#Start",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#startnode",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-StartNode",
    "public/CsoundAudioNode.js~CsoundAudioNode#StartNode",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#stop",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-Stop",
    "public/CsoundAudioNode.js~CsoundAudioNode#Stop",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#stoppromise",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-StopPromise",
    "public/CsoundAudioNode.js~CsoundAudioNode#StopPromise",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#tableget",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-TableGet",
    "public/CsoundAudioNode.js~CsoundAudioNode#TableGet",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#tablelength",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-TableLength",
    "public/CsoundAudioNode.js~CsoundAudioNode#TableLength",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#tableset",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-TableSet",
    "public/CsoundAudioNode.js~CsoundAudioNode#TableSet",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#cleanup",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-cleanup",
    "public/CsoundAudioNode.js~CsoundAudioNode#cleanup",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#compilecsd",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-compileCsd",
    "public/CsoundAudioNode.js~CsoundAudioNode#compileCsd",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#compilecsdtext",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-compileCsdText",
    "public/CsoundAudioNode.js~CsoundAudioNode#compileCsdText",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#compileorc",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-compileOrc",
    "public/CsoundAudioNode.js~CsoundAudioNode#compileOrc",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#constructor",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-constructor-constructor",
    "public/CsoundAudioNode.js~CsoundAudioNode#constructor",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#destroy",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-destroy",
    "public/CsoundAudioNode.js~CsoundAudioNode#destroy",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#evalcode",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-evalCode",
    "public/CsoundAudioNode.js~CsoundAudioNode#evalCode",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#get0dbfs",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-get0dBFS",
    "public/CsoundAudioNode.js~CsoundAudioNode#get0dBFS",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getapiversion",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getAPIVersion",
    "public/CsoundAudioNode.js~CsoundAudioNode#getAPIVersion",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getcontrolchannel",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getControlChannel",
    "public/CsoundAudioNode.js~CsoundAudioNode#getControlChannel",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getcurrenttimesamples",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getCurrentTimeSamples",
    "public/CsoundAudioNode.js~CsoundAudioNode#getCurrentTimeSamples",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getenv",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getEnv",
    "public/CsoundAudioNode.js~CsoundAudioNode#getEnv",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getfiledata",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getFileData",
    "public/CsoundAudioNode.js~CsoundAudioNode#getFileData",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getinputname",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getInputName",
    "public/CsoundAudioNode.js~CsoundAudioNode#getInputName",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getksmps",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getKsmps",
    "public/CsoundAudioNode.js~CsoundAudioNode#getKsmps",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getnchnls",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getNchnls",
    "public/CsoundAudioNode.js~CsoundAudioNode#getNchnls",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getnchnlsinput",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getNchnlsInput",
    "public/CsoundAudioNode.js~CsoundAudioNode#getNchnlsInput",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getoutputname",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getOutputName",
    "public/CsoundAudioNode.js~CsoundAudioNode#getOutputName",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getscoreoffsetseconds",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getScoreOffsetSeconds",
    "public/CsoundAudioNode.js~CsoundAudioNode#getScoreOffsetSeconds",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getscoretime",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getScoreTime",
    "public/CsoundAudioNode.js~CsoundAudioNode#getScoreTime",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getsr",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getSr",
    "public/CsoundAudioNode.js~CsoundAudioNode#getSr",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getstringchannel",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getStringChannel",
    "public/CsoundAudioNode.js~CsoundAudioNode#getStringChannel",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#getversion",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-getVersion",
    "public/CsoundAudioNode.js~CsoundAudioNode#getVersion",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#input",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-input",
    "public/CsoundAudioNode.js~CsoundAudioNode#input",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#inputmessage",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-inputMessage",
    "public/CsoundAudioNode.js~CsoundAudioNode#inputMessage",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#isplaying",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-isPlaying",
    "public/CsoundAudioNode.js~CsoundAudioNode#isPlaying",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#isscorepending",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-isScorePending",
    "public/CsoundAudioNode.js~CsoundAudioNode#isScorePending",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#is_playing",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-is_playing",
    "public/CsoundAudioNode.js~CsoundAudioNode#is_playing",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#is_realtime",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-is_realtime",
    "public/CsoundAudioNode.js~CsoundAudioNode#is_realtime",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#killinstance",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-killInstance",
    "public/CsoundAudioNode.js~CsoundAudioNode#killInstance",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#message",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-message",
    "public/CsoundAudioNode.js~CsoundAudioNode#message",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#message_callback",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-message_callback",
    "public/CsoundAudioNode.js~CsoundAudioNode#message_callback",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#onmessage",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-onMessage",
    "public/CsoundAudioNode.js~CsoundAudioNode#onMessage",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#output",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-output",
    "public/CsoundAudioNode.js~CsoundAudioNode#output",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#perform",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-perform",
    "public/CsoundAudioNode.js~CsoundAudioNode#perform",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#performcsd",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-performCsd",
    "public/CsoundAudioNode.js~CsoundAudioNode#performCsd",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#performorc",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-performOrc",
    "public/CsoundAudioNode.js~CsoundAudioNode#performOrc",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#readscore",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-readScore",
    "public/CsoundAudioNode.js~CsoundAudioNode#readScore",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#reset",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-reset",
    "public/CsoundAudioNode.js~CsoundAudioNode#reset",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#reset_",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-reset_",
    "public/CsoundAudioNode.js~CsoundAudioNode#reset_",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#resolvecleanup",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-resolveCleanup",
    "public/CsoundAudioNode.js~CsoundAudioNode#resolveCleanup",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#resolvecompilecsdtext",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-resolveCompileCsdText",
    "public/CsoundAudioNode.js~CsoundAudioNode#resolveCompileCsdText",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#resolvecompileorc",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-resolveCompileOrc",
    "public/CsoundAudioNode.js~CsoundAudioNode#resolveCompileOrc",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#resolvegetcontrolchannel",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-resolveGetControlChannel",
    "public/CsoundAudioNode.js~CsoundAudioNode#resolveGetControlChannel",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#resolvegetfiledata",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-resolveGetFileData",
    "public/CsoundAudioNode.js~CsoundAudioNode#resolveGetFileData",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#resolvegetscoretime",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-resolveGetScoreTime",
    "public/CsoundAudioNode.js~CsoundAudioNode#resolveGetScoreTime",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#resolveisplaying",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-resolveIsPlaying",
    "public/CsoundAudioNode.js~CsoundAudioNode#resolveIsPlaying",
    "member"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#resolvereadscore",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-resolveReadScore",
    "public/CsoundAudioNode.js~CsoundAudioNode#resolveReadScore",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#resolvereset",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-resolveReset",
    "public/CsoundAudioNode.js~CsoundAudioNode#resolveReset",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#resolvestop",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-resolveStop",
    "public/CsoundAudioNode.js~CsoundAudioNode#resolveStop",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#start",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-start",
    "public/CsoundAudioNode.js~CsoundAudioNode#start",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#startnode",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-startNode",
    "public/CsoundAudioNode.js~CsoundAudioNode#startNode",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#stop",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-stop",
    "public/CsoundAudioNode.js~CsoundAudioNode#stop",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#tableget",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-tableGet",
    "public/CsoundAudioNode.js~CsoundAudioNode#tableGet",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#tablelength",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-tableLength",
    "public/CsoundAudioNode.js~CsoundAudioNode#tableLength",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#tableset",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-method-tableSet",
    "public/CsoundAudioNode.js~CsoundAudioNode#tableSet",
    "method"
  ],
  [
    "public/csoundaudionode.js~csoundaudionode#usermediaaudioinputnode",
    "class/public/CsoundAudioNode.js~CsoundAudioNode.html#instance-member-userMediaAudioInputNode",
    "public/CsoundAudioNode.js~CsoundAudioNode#userMediaAudioInputNode",
    "member"
  ],
  [
    "public/silencio.js",
    "file/public/Silencio.js.html",
    "public/Silencio.js",
    "file"
  ],
  [
    "public/csoundac.mjs",
    "file/public/csoundac.mjs.html",
    "public/csoundac.mjs",
    "file"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acc",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-method-acC",
    "public/csoundac.mjs~ChordPatterns#acC",
    "method"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acci",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-method-acCI",
    "public/csoundac.mjs~ChordPatterns#acCI",
    "method"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acci_center",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCI_center",
    "public/csoundac.mjs~ChordPatterns#acCI_center",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acci_counter",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCI_counter",
    "public/csoundac.mjs~ChordPatterns#acCI_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acci_flip",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCI_flip",
    "public/csoundac.mjs~ChordPatterns#acCI_flip",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acck",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-method-acCK",
    "public/csoundac.mjs~ChordPatterns#acCK",
    "method"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acck_counter",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCK_counter",
    "public/csoundac.mjs~ChordPatterns#acCK_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acck_state",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCK_state",
    "public/csoundac.mjs~ChordPatterns#acCK_state",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acco",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-method-acCO",
    "public/csoundac.mjs~ChordPatterns#acCO",
    "method"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accop",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-method-acCOP",
    "public/csoundac.mjs~ChordPatterns#acCOP",
    "method"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accop_counter",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCOP_counter",
    "public/csoundac.mjs~ChordPatterns#acCOP_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acco_counter",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCO_counter",
    "public/csoundac.mjs~ChordPatterns#acCO_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accq",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-method-acCQ",
    "public/csoundac.mjs~ChordPatterns#acCQ",
    "method"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accq_counter",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCQ_counter",
    "public/csoundac.mjs~ChordPatterns#acCQ_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accq_semitones",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCQ_semitones",
    "public/csoundac.mjs~ChordPatterns#acCQ_semitones",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accrp",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-method-acCRP",
    "public/csoundac.mjs~ChordPatterns#acCRP",
    "method"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accrp_counter",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCRP_counter",
    "public/csoundac.mjs~ChordPatterns#acCRP_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acct",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-method-acCT",
    "public/csoundac.mjs~ChordPatterns#acCT",
    "method"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acct_counter",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCT_counter",
    "public/csoundac.mjs~ChordPatterns#acCT_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acct_semitones",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCT_semitones",
    "public/csoundac.mjs~ChordPatterns#acCT_semitones",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accv",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-method-acCV",
    "public/csoundac.mjs~ChordPatterns#acCV",
    "method"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accvv",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-method-acCVV",
    "public/csoundac.mjs~ChordPatterns#acCVV",
    "method"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accvvl",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-method-acCVVL",
    "public/csoundac.mjs~ChordPatterns#acCVVL",
    "method"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accvvl_counter",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCVVL_counter",
    "public/csoundac.mjs~ChordPatterns#acCVVL_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accvv_counter",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCVV_counter",
    "public/csoundac.mjs~ChordPatterns#acCVV_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#accv_counter",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acCV_counter",
    "public/csoundac.mjs~ChordPatterns#acCV_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acc_chord_string",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acC_chord_string",
    "public/csoundac.mjs~ChordPatterns#acC_chord_string",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acc_counter",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acC_counter",
    "public/csoundac.mjs~ChordPatterns#acC_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#acs_chord_string",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-acS_chord_string",
    "public/csoundac.mjs~ChordPatterns#acS_chord_string",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#ac_chord",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-ac_chord",
    "public/csoundac.mjs~ChordPatterns#ac_chord",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#ac_modality",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-ac_modality",
    "public/csoundac.mjs~ChordPatterns#ac_modality",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#ac_scale",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-ac_scale",
    "public/csoundac.mjs~ChordPatterns#ac_scale",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#constructor",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-constructor-constructor",
    "public/csoundac.mjs~ChordPatterns#constructor",
    "method"
  ],
  [
    "public/csoundac.mjs~chordpatterns#flip",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-flip",
    "public/csoundac.mjs~ChordPatterns#flip",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#prior_chord",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-prior_chord",
    "public/csoundac.mjs~ChordPatterns#prior_chord",
    "member"
  ],
  [
    "public/csoundac.mjs~chordpatterns#value",
    "class/public/csoundac.mjs~ChordPatterns.html#instance-member-value",
    "public/csoundac.mjs~ChordPatterns#value",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acp",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-method-acP",
    "public/csoundac.mjs~PitvPatterns#acP",
    "method"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpc",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-method-acPC",
    "public/csoundac.mjs~PitvPatterns#acPC",
    "method"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpc_counter",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPC_counter",
    "public/csoundac.mjs~PitvPatterns#acPC_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpi",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-method-acPI",
    "public/csoundac.mjs~PitvPatterns#acPI",
    "method"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpi_i",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPI_I",
    "public/csoundac.mjs~PitvPatterns#acPI_I",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpi_counter",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPI_counter",
    "public/csoundac.mjs~PitvPatterns#acPI_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpo",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-method-acPO",
    "public/csoundac.mjs~PitvPatterns#acPO",
    "method"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpo_o",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPO_O",
    "public/csoundac.mjs~PitvPatterns#acPO_O",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpo_counter",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPO_counter",
    "public/csoundac.mjs~PitvPatterns#acPO_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpo_value",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPO_value",
    "public/csoundac.mjs~PitvPatterns#acPO_value",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpp",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-method-acPP",
    "public/csoundac.mjs~PitvPatterns#acPP",
    "method"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpp_p",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPP_P",
    "public/csoundac.mjs~PitvPatterns#acPP_P",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpp_counter",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPP_counter",
    "public/csoundac.mjs~PitvPatterns#acPP_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpt",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-method-acPT",
    "public/csoundac.mjs~PitvPatterns#acPT",
    "method"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpt_t",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPT_T",
    "public/csoundac.mjs~PitvPatterns#acPT_T",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpt_counter",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPT_counter",
    "public/csoundac.mjs~PitvPatterns#acPT_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpv",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-method-acPV",
    "public/csoundac.mjs~PitvPatterns#acPV",
    "method"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpvs_counter",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPVS_counter",
    "public/csoundac.mjs~PitvPatterns#acPVS_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpvv",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-method-acPVV",
    "public/csoundac.mjs~PitvPatterns#acPVV",
    "method"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpvvl",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-method-acPVVL",
    "public/csoundac.mjs~PitvPatterns#acPVVL",
    "method"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpvv_counter",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPVV_counter",
    "public/csoundac.mjs~PitvPatterns#acPVV_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpv_v",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPV_V",
    "public/csoundac.mjs~PitvPatterns#acPV_V",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acpv_counter",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acPV_counter",
    "public/csoundac.mjs~PitvPatterns#acPV_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#acp_counter",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-acP_counter",
    "public/csoundac.mjs~PitvPatterns#acP_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#ac_chord",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-ac_chord",
    "public/csoundac.mjs~PitvPatterns#ac_chord",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#constructor",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-constructor-constructor",
    "public/csoundac.mjs~PitvPatterns#constructor",
    "method"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#pitv",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-pitv",
    "public/csoundac.mjs~PitvPatterns#pitv",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns#prior_chord",
    "class/public/csoundac.mjs~PitvPatterns.html#instance-member-prior_chord",
    "public/csoundac.mjs~PitvPatterns#prior_chord",
    "member"
  ],
  [
    "public/csoundac.mjs~pitvpatterns.acpi_counter",
    "class/public/csoundac.mjs~PitvPatterns.html#static-member-acPI_counter",
    "public/csoundac.mjs~PitvPatterns.acPI_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#accvv",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-method-acCVV",
    "public/csoundac.mjs~ScalePatterns#acCVV",
    "method"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acs",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-method-acS",
    "public/csoundac.mjs~ScalePatterns#acS",
    "method"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acscv",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-method-acSCV",
    "public/csoundac.mjs~ScalePatterns#acSCV",
    "method"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acscv_counter",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-acSCV_counter",
    "public/csoundac.mjs~ScalePatterns#acSCV_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acsm",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-method-acSM",
    "public/csoundac.mjs~ScalePatterns#acSM",
    "method"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acsm_counter",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-acSM_counter",
    "public/csoundac.mjs~ScalePatterns#acSM_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acsm_index",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-acSM_index",
    "public/csoundac.mjs~ScalePatterns#acSM_index",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acso",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-method-acSO",
    "public/csoundac.mjs~ScalePatterns#acSO",
    "method"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acso_counter",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-acSO_counter",
    "public/csoundac.mjs~ScalePatterns#acSO_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acss",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-method-acSS",
    "public/csoundac.mjs~ScalePatterns#acSS",
    "method"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acss_counter",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-acSS_counter",
    "public/csoundac.mjs~ScalePatterns#acSS_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acss_scale_step",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-acSS_scale_step",
    "public/csoundac.mjs~ScalePatterns#acSS_scale_step",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acst",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-method-acST",
    "public/csoundac.mjs~ScalePatterns#acST",
    "method"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acst_counter",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-acST_counter",
    "public/csoundac.mjs~ScalePatterns#acST_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acst_scale_steps",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-acST_scale_steps",
    "public/csoundac.mjs~ScalePatterns#acST_scale_steps",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acsv",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-method-acSV",
    "public/csoundac.mjs~ScalePatterns#acSV",
    "method"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acsvvl",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-method-acSVVL",
    "public/csoundac.mjs~ScalePatterns#acSVVL",
    "method"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acsv_counter",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-acSV_counter",
    "public/csoundac.mjs~ScalePatterns#acSV_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acs_counter",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-acS_counter",
    "public/csoundac.mjs~ScalePatterns#acS_counter",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#acs_scale_string",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-acS_scale_string",
    "public/csoundac.mjs~ScalePatterns#acS_scale_string",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#ac_chord",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-ac_chord",
    "public/csoundac.mjs~ScalePatterns#ac_chord",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#ac_scale",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-ac_scale",
    "public/csoundac.mjs~ScalePatterns#ac_scale",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#constructor",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-constructor-constructor",
    "public/csoundac.mjs~ScalePatterns#constructor",
    "method"
  ],
  [
    "public/csoundac.mjs~scalepatterns#prior_chord",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-prior_chord",
    "public/csoundac.mjs~ScalePatterns#prior_chord",
    "member"
  ],
  [
    "public/csoundac.mjs~scalepatterns#voices",
    "class/public/csoundac.mjs~ScalePatterns.html#instance-member-voices",
    "public/csoundac.mjs~ScalePatterns#voices",
    "member"
  ],
  [
    "public/statefulpatterns.mjs",
    "file/public/statefulpatterns.mjs.html",
    "public/statefulpatterns.mjs",
    "file"
  ],
  [
    "public/statefulpatterns.mjs~statefulpatterns#constructor",
    "class/public/statefulpatterns.mjs~StatefulPatterns.html#instance-constructor-constructor",
    "public/statefulpatterns.mjs~StatefulPatterns#constructor",
    "method"
  ],
  [
    "public/statefulpatterns.mjs~statefulpatterns#registerpatterns",
    "class/public/statefulpatterns.mjs~StatefulPatterns.html#instance-method-registerPatterns",
    "public/statefulpatterns.mjs~StatefulPatterns#registerPatterns",
    "method"
  ]
]